[project]
name = "novelWriter.io"
version = "1.0"
description = "The novelWriter website"
readme = "README.md"
dependencies = [
    "pydata-sphinx-theme>=0.15",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-favicon",
    "sphinx<7.0",
]
